[devshell]
packages = [
  "alejandra",
  "dprint",
  "nodejs-16_x",
  "nodePackages.pnpm",
]

[[commands]]
package = "treefmt"
category = "formatter"

[[env]]
name = "PATH"
eval = "$PATH:$PRJ_ROOT/node_modules/.bin"
